name: Code Quality

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  code_quality:
    name: Code Quality Check
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
          Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
          & "$env:PYTHONPATH\python.exe" get-pip.py

      - name: Install Flake8
        run: |
          & "$env:PYTHONPATH\python.exe" -m pip install flake8

      - name: Run Flake8
        run: |
          & "$env:PYTHONPATH\python.exe" -m flake8 --exclude=venv --config=.flake8
